name: UniqueSDK

############
# Options
############

options:
  minimumXcodeGenVersion: 2.10
  groupSortPosition: top
  generateEmptyDirectories: true
  deploymentTarget: 
    iOS: "13.0"


############
# Packages
############



############
# Targets
############

targets:
  UniqueSDK:
    type: framework
    platform: iOS
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: "com.UniqueSdk.UniqueSdk"
    scheme:
      gatherCoverageData: true
    info:
      path: UniqueSDK/Supporting Files/Info.plist
    sources:
      - UniqueSDK
      - path: UniqueSDK/Supporting Files/UniqueSDK.h
        buildPhase: headers
        headerVisibility: public
    
  UniqueSDKDemo:
    type: application
    platform: iOS
 
    # devices: [iPhone, iPad]
    settings:
      base:
        SWIFT_VERSION: 5.5.2
        # TARGETED_DEVICE_FAMILY: 1
        CODE_SIGN_STYLE: "Manual"
        ENABLE_BITCODE: false
        DEVELOPMENT_TEAM: 3382SF795H
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: "apple-generic"
        USE_SWIFT_RESPONSE_FILE: true
        OTHER_LDFLAGS: [-ObjC]
    info:
      path: UniqueSDKDemo/Supporting Files/Info.plist
      properties:
        UILaunchStoryboardName: "Launch Screen"
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]

        NSUserTrackingUsageDescription: "Идентификатор будет использоваться для сбора данных о сбоях и действиях в приложении для улучшения функциональности и взаимодействия с пользователем"
        CFBundleDisplayName: "UniqueSDKDemo"
        CFBundleShortVersionString: "1.0.0"
        CFBundleIdentifier: "com.UniqueSDKDemo.UniqueSDKDemo"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIRequiresFullScreen: true
        CFBundleDevelopmentRegion: "ru"
        CFBundleLocalizations: ["ru"]
        ITSAppUsesNonExemptEncryption: false
        UIUserInterfaceStyle: "Light"
        UIApplicationSceneManifest:
            UIApplicationSupportsMultipleScenes: false
            UISceneConfigurations:
                UIWindowSceneSessionRoleApplication:
                    - UISceneConfigurationName: "Default Configuration"
                      UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
                      UISceneStoryboardFile: "Main"

#            UISceneConfigurations:
#                - UIWindowSceneSessionRoleApplication:
#                    - UISceneConfigurationName: "Default Configuration"
#                    UISceneDelegateClassName: "$(PRODUCT_MODULE_NAME).SceneDelegate"
#                    UISceneStoryboardFile: "Main"
                    
                    
#    postCompileScripts:
#      - path: swiftlint.sh
#        name: SwiftLint
    sources:
      - path: UniqueSDKDemo
      - path: UniqueSDKDemo/Assets.xcassets
    dependencies:
      - target: UniqueSDK

targetTemplates:
  Framework:
    type: framework
    platform: iOS
    deploymentTarget: 13.0
    settings:
      base:
        MARKETING_VERSION: 1.0
        SWIFT_VERSION: 5.0.0
        TARGETED_DEVICE_FAMILY: 1,2
        SUPPORTS_MACCATALYST: NO


#name: HELLO options: deploymentTarget: iOS: 13.0 createIntermediateGroups: true bundleIdPrefix: com.milkyo transitivelyLinkDependencies: true targets: HELLO: platform: iOS deploymentTarget: 13.1.3 type: application info: path: HELLO/Supporting Files/Info.plist
#properties:
#    CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
#    UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
#    UILaunchStoryboardName: LaunchScreen
#    UIApplicationSceneManifest:
#        UIApplicationSupportsMultipleScenes: false
#        UISceneConfigurations:
#            UIWindowSceneSessionRoleApplication:
#             - UISceneConfigurationName: Default Configuration
#             UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
#settings: base: SWIFT_VERSION: 5.2 TARGETED_DEVICE_FAMILY: 1,2 FRAMEWORK_SEARCH_PATHS: [$(inherited), $(PROJECT_DIR)] sources: - HELLO/Sources - HELLO/Supporting Files
#
